### ISSUE TITLE
Error in termination of run_game function

### ISSUE THREAD

**Issue by CapucineBoudin** [clementcaron/game_of_life-caron-cdof2#3]
In the run_game function, there is a check to break the loop if the new grid is the same as the current grid: if new_grid == grid: break. This check assumes that if the grids are the same, the simulation has reached a stable state and should stop. However, it's possible for the game to reach a stable state and still have periodic patterns that repeat. In such cases, the simulation will not terminate correctly. Consider using a more robust termination condition that takes into account the behavior of the Game of Life

**Comment by clementcaron** [comment]
Thank you for your feedback on the termination condition in the run_game function of my code. You're right about the limitation of the current approach. It's adept at detecting static configurations, but it fails to account for periodic patterns, which are a fundamental aspect of the Game of Life.

Periodic patterns do not change back to the original state in consecutive generations but may do so over multiple generations (as you can see here: https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life#Examples_of_patterns). To address this, I can implement a more robust termination condition. This will involve maintaining a history of past grid states and checking for repetitions over a series of generations, rather than just comparing consecutive ones. This approach, while more memory-intensive, will accurately detect periodic as well as static states, leading to a more precise termination of the simulation when a repeating pattern is identified.
